### ISSUE TITLE
docs for "mode" argument to write-table?

### ISSUE THREAD

**Issue by jbclements** [massung/tabular-asa#8]
First off: many thanks for working on this, I'm using tabular-asa a whole lot these days!

It looks like there's no documentation for the `mode` flag to write-table. Based on some experiments, it looks to me like it controls the style of printing used for the table elements. If I'm right about this, I think a sentence such as the following would be a welcome addition to the documentation for `write-table`:

If @racket[mode] is #t, the table elements are printed in the style of `print`. If it is `false`, they are printed in the style of `display`.

**Comment by massung** [comment]
Thanks for the kind words! If you don't mind me asking, what do you use it for? Actual work or as a teaching aid, something else?

> If `@racket[mode]` is `#t`, the table elements are printed in the style of print. If it is false, they are printed in the style of display.

That seems like good wording. Thanks for the suggestion!

**Comment by jbclements** [comment]
Made this pull request, #7 . In answer to your question, the most pressing need for me is just in replacing a ton of class management stuff I used to do with s-expressions. I found that maintaining code that was a massive pile of s-expression manipulation was really painful; keeping them as tables makes for way more readable code.

**Comment by jbclements** [comment]
Ooh rats, I didn't mean #7 in the previous comment, I meant #9 . Mea culpa.

**Comment by jbclements** [comment]
resolved by #9
